version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - main
image: Visual Studio 2022
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore AiContext.sln --verbosity q

build_script:
  - cmd: dotnet build AiContext.sln --configuration Release --no-restore
after_build:
  # For once the build has completed
  - cmd: dotnet pack AiContext.sln --configuration Release --no-build --output packages --include-symbols --include-source
artifacts:
  - path: "packages/**/*.nupkg"
    name: NugetPackages

clone_depth: 1
test_script:
  - cmd: dotnet test AiContext.sln
deploy:
  - provider: NuGet
    api_key:
      secure: vYVb0CR1e2NhwlWxxSXtzqfmiZf5TshSl/LFPBy7oBxztjSVrFLTLQpP8Xn66kdR

    skip_symbols: false
    artifact: /.*(\.|\.s)nupkg/
    on:
      branch: main
