version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - main
image: Visual Studio 2022
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore AiContext.slnx --verbosity q

build_script:
  - cmd: dotnet build AiContext.slnx --configuration Release --no-restore
after_build:
  # For once the build has completed
  - cmd: dotnet pack AiContext.slnx --configuration Release --no-build --output nupkg --include-symbols --include-source
artifacts:
  - path: "src/**/*.nupkg"
    name: NugetPacakges